version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  ballastlane:
    image: ${DOCKER_REGISTRY-}ballastlane
    build:
      context: .
      dockerfile: BallastLane\Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=tempdb;User Id=sa;Password=YourStrong!Passw0rd;"
      ConnectionStrings__DefaultConnectionStart: "Server=db;Database=tempdb;User Id=sa;Password=YourStrong!Passw0rd;"


volumes:
  sqlserver-data:
